//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC_MVC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propertiess
    {
        public string propertyNo { get; set; }
        public string pAddress { get; set; }
        public string ownerNo { get; set; }
    
        public virtual Owner Owner { get; set; }
    }
}
